var messages_en = {
    'ajax.network.error': 'Network error, please check your internet connection',
    'and': 'and',
    'and.show.up.to': 'and show up to',
    'any.language': 'Any Language',
    'close.button': 'Close',
    'collections': 'Collections',
    'corpus.search.corpusbox': 'Search for collection',
    'corpusview.amountOfSubcollections': '({amount} subcollections)',
    'corpusview.collapse': ' Collapse ',
    'corpusview.expand': ' Expand ',
    'corpusview.homepage': '– Homepage',
    'corpusview.howManyCollectionsAreShown': 'Showing {visible} out of {total} (sub)collections.',
    'cql.query.name': 'Text layer Contextual Query Language (CQL)',
    'cql.query.searchLabel': 'Text layer CQL query',
    'cql.query.searchPlaceholder': 'Elephant',
    'deselect.all': ' Deselect all',
    'endpoint.translation': 'hits per endpoint',
    'federated.content.search': 'Federated Content Search',
    'fcsql.query.name': 'Multi-layer Federated Content Search Query Language (FCS-QL)',
    'fcsql.query.searchLabel': 'Multi-layer FCS query',
    'fcsql.query.searchPlaceholder': "[word = 'annotation'][word = 'focused']",
    'front.page.all.collections.selected': 'All available collections ({amount})',
    'front.page.one.collection.selected': '1 selected collection',
    'front.page.some.collections.selected': '{amount} selected collections',
    'in': 'in',
    'is': 'is',
    'is.not': 'is not',
    'language.radio.byGuess': 'Filter results by using a language detector',
    'language.radio.byMeta': 'Use the collections\' specified language to filter results',
    'language.radio.byMetaAndGuess': 'First use the collections specified language then also use a language detector',
    'or': 'or',
    'orarg.language': 'language',
    'orarg.lemma': 'lemma',
    'orarg.partofspeech': 'part-of-speech',
    'orarg.properNoun': 'Proper Noun',
    'orarg.word': 'word',
    'repeatMenu.repeat': 'repeat',
    'repeatMenu.times': 'times',
    'repeatMenu.to': 'to',
    'resultmixin.causedBy': 'Caused by: ',
    'resultmixin.display.adv': 'Display as AdvancedDataView (ADV)',
    'resultmixin.display.kwic': 'Display as Key Word In Context',
    'resultmixin.download': ' Download ',
    'resultmixin.download.csv': 'As CSV file',
    'resultmixin.download.json': 'As JSON file',
    'resultmixin.download.xml': 'As XML file',
    'resultmixin.exception': 'Exception: ',
    'results.howManyMatchingCollectionsFound': '{amount} matching collections found',
    'results.renderProgressMessage': '{found} matching collections found in {done} searched collections',
    'results.view.button': 'View',
    'search.for': 'Search for',
    'select.all': ' Select all',
    'select.corpora.error': 'Please select a collection to search into',
    'select.language': 'Select Language',
    'zoomedresult.moreResults': 'More Results',
    'zoomedresult.noMoreResults': 'No other results available for this query',
    'zoomedresult.pleaseWait': 'Retrieving results, please wait...',
};

export default messages_en;